Debug coverage again.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -134,10 +134,11 @@ jobs:
       - name: Combine coverage reports
         run: |
           pip install coverage
-          cp coverage-dgl/coverage.dgl .
-          cp coverage-pyg/coverage.pyg .
+          ls *
+          # cp coverage-dgl/coverage.dgl .
+          # cp coverage-pyg/coverage.pyg .
           echo "Combining coverage files..."
-          coverage combine coverage* || echo "Warning: coverage combine failed"
+          coverage combine coverage.* || echo "Warning: coverage combine failed"
           coverage xml -o coverage.xml || echo "Warning: coverage xml failed"
       - name: Upload coverage reports to Codecov
         uses: codecov/codecov-action@v4
